### ISSUE TITLE
Terms And Privacy Policy Feature - 

### ISSUE THREAD

**Issue by claudiodaud** [grpaiva/jetstream-flux#2]
![image](https://github.com/user-attachments/assets/1bc2748a-5bed-43fa-882b-f66e64b160a4)

 `@if (Laravel\Jetstream\Jetstream::hasTermsAndPrivacyPolicyFeature())
                    {{-- <flux:field variant="inline">
                        <flux:checkbox wire:model="terms" /> 
                        
                        <flux:label>
                            {!! __('I agree to the :terms_of_service and :privacy_policy', [
                                    'terms_of_service' => '<a target="_blank" href="'.route('terms.show').'" class="underline text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:focus:ring-offset-gray-800">'.__('Terms of Service').'</a>',
                                    'privacy_policy' => '<a target="_blank" href="'.route('policy.show').'" class="underline text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:focus:ring-offset-gray-800">'.__('Privacy Policy').'</a>',
                            ]) !!}
                        </flux:label>
                    </flux:field> --}}

                    <div class="mt-4">
                        <x-label for="terms">
                            <div class="flex items-center">
                                <x-checkbox name="terms" id="terms" required />

                                <div class="ms-2">
                                    {!! __('I agree to the :terms_of_service and :privacy_policy', [
                                            'terms_of_service' => '<a target="_blank" href="'.route('terms.show').'" class="underline text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:focus:ring-offset-gray-800">'.__('Terms of Service').'</a>',
                                            'privacy_policy' => '<a target="_blank" href="'.route('policy.show').'" class="underline text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:focus:ring-offset-gray-800">'.__('Privacy Policy').'</a>',
                                    ]) !!}
                                </div>
                            </div>
                        </x-label>
                    </div>
                    
                @endif
`

grpaiva greetings and congratulations, great job modifying the jetstream views to work with flux, I was also working on it and it was not easy, I tell you that the terms and policies checkbox does not work, when checking the validation it continues, appreciating that the field is required , I saw that you linked it with wire:model="terms" but I don't quite understand how to implement it.

Many greetings 
I really appreciate your great work

**Comment by grpaiva** [comment]
Hey @claudiodaud,

Appreciate the feedback! You're right, we should be using input `name="terms"` instead of `wire:model`. 

While fixing this, I think I spotted a Flux UI issue: it looks like the "name" attribute isn't being forwarded to the final `<ui-checkbox>` element.

For now, I’ve implemented a workaround using Alpine (available in v1.0.5). I’ll also try to check in with Caleb to confirm if this is a Flux UI issue or if there's something I might have overlooked. 

I get it—some might say I’m pushing Flux UI components a bit too hard, and whether this workaround is the best idea is totally up for debate. But for now, I’d rather keep things consistent with Flux UI for the form elements.

Here’s the workaround:

```html
<flux:field variant="inline" x-data="{ terms: false }">
    <input type="checkbox" name="terms" id="terms" x-model="terms" class="hidden"/>
    <flux:checkbox x-model="terms"/>
    <flux:label>
        {!! __('I agree to the :terms_of_service and :privacy_policy', [
                'terms_of_service' => '<a target="_blank" href="'.route('terms.show').'" class="underline text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:focus:ring-offset-gray-800">'.__('Terms of Service').'</a>',
                'privacy_policy' => '<a target="_blank" href="'.route('policy.show').'" class="underline text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 rounded-md focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:focus:ring-offset-gray-800">'.__('Privacy Policy').'</a>',
        ]) !!}
    </flux:label>
</flux:field>
```
